name: main

on:
  push:
    branches:
      - "**"

jobs:
  Release:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: step_release_please
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      # - name: install
      #   run: |
      #     yarn install

      # - name: release
      #   run: yarn run release-it
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}